/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AreaPage: typeof import('./src/components/areaPage.vue')['default']
    Echarts: typeof import('./src/components/echarts.vue')['default']
    FontSvg: typeof import('./src/components/fontSvg.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrolllList: typeof import('./src/components/scrolllList.vue')['default']
  }
}
